### ISSUE TITLE
Documentation: `p0` automatic setting in `empbayes_fit`

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/lsqfit#12]
I am using `empbayes_fit` and I want to specify the `p0` parameter to `nonlinear_fit`. However I guessed that `empbayes_fit` would set `p0` each time to the result of the last iteration as an optimization, and I wondered if me explicitly setting `p0` would break this and start the fit each time from the same place. So I looked into the code and determined that `empbayes_fit` will override my `p0` after the first iteration. I think this behavior should be described in the docstring of `empbayes_fit`.

**Comment by gplepage** [comment]
The treatment of ``p0`` in empbayes_fit was incorrect. I have fixed it in v13.0. Now ``empbayes_fit`` has a keyword ``p0`` which is used by the first fit, with subsequent fits updating ``p0`` to improve (hopefully) performance (as before). If ``fitargs`` returns a value for ``p0`` it will be used in every fit.

**Comment by Gattocrucco** [comment]
Thanks.
