### ISSUE TITLE
Failed install with new gvar version

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/lsqfit#13]
After the gvar release 11.11.3, which fixes [#16](https://github.com/gplepage/gvar/issues/16), lsqfit is not installing anymore. The first reported error is

```
      [1/2] Cythonizing src/lsqfit/_gsl.pyx

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      # GNU General Public License for more details.
      
      cimport numpy
      cimport cython
      cimport gvar
             ^
      ------------------------------------------------------------
      
      src/lsqfit/_gsl.pyx:16:8: 'gvar.pxd' not found
```

and the subsequent ones seem all related to missing gvar symbols. The error appears also with pip < 23.1 on a clean virtual environment.

**Comment by gplepage** [comment]
Thanks for the quick  feedback. This looks like a gvar problem (with the installation). gvar installation has a couple of issues that I am working on. Should have them fixed soon.
