### ISSUE TITLE
Installation fails if pip >= 23.1

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/lsqfit#14]
The installation fails due to not finding numpy at build time iff pip >= 23.1. I guess it's the same problem as [gvar/#16](https://github.com/gplepage/gvar/issues/16).

**Comment by gplepage** [comment]
Yes, you are quite likely correct. I need to apply the same fixes here, which I will do shortly.

**Comment by gplepage** [comment]
This might be fixed by lsqfit version 13.0.1.

**Comment by Gattocrucco** [comment]
It works, thanks.
