### ISSUE TITLE
How to cite lsqfit in an article

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/lsqfit#4]
I wish to cite the lsqfit program in an article, I was about to use
    \bibitem{lsqfit}
    Lepage, G.\ P.\ (2008--2019).
    \emph{\texttt{lsqfit}: Utilities for nonlinear least-squares fits}.
    \url{https://github.com/gplepage/lsqfit}
do you have a preference about this?

**Comment by gplepage** [comment]
That would be fine. The journal may want a digital object identifier (DOI). For version 11.2 (current version) one would be DOI: 10.5281/zenodo.2613676. 

Thanks for checking with me.

**Comment by gplepage** [comment]
I am closing this issue.
